# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle build
      
    - name: Slack Notify Fail
      if: failure()
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: group-dev
        SLACK_COLOR: "#FF0000"
        SLACK_USERNAME: 'Github Action'
        SLACK_ICON: https://avatars.githubusercontent.com/u/9919?s=48&v=4
        SLACK_TITLE: Build Failure - ${{ github.event.pull_request.title }}
        SLACK_MESSAGE: PR Url - ${{ github.event.pull_request.url }} - 빌드 및 테스트 실패
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Slack Notify Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.1.0
      env:
        SLACK_CHANNEL: group-dev
        SLACK_COLOR: "#7EB33D"
        SLACK_USERNAME: 'Github Action'
        SLACK_ICON: https://avatars.githubusercontent.com/u/9919?s=48&v=4
        SLACK_TITLE: Build Success - ${{ github.event.pull_request.title }}
        SLACK_MESSAGE: PR Url - ${{ github.event.pull_request.url }} - 빌드 및 테스트 성공
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        
    - name: Make deploy key
      if: success()
      env:
        GH_ACTION_DEPLOY: ${{ secrets.GH_ACTION_DEPLOY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
    - name: clone rest-json
      if: success()
      run: |
        cd ~
        git clone git@github.com:non-terview/rest-json.github.io.git rest_json
        
    - name: Copy static file to rest-json
      if: success()
      run: |
        cd ~
        cp -r /home/runner/work/on-terview-api/on-terview-api/src/main/resources/static/docs ~/rest_json/
        
    - name: Push rest-json
      if: success()
      run: |
        cd ~/rest_json
        git config --global user.email "aistarteverything@gmail.com"
        git config --global user.name "askePhoenix"
        git add .
        git commit -m "(git -C ~/rest_json log --format=%B -n 1)"
        git push origin master

